// import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// Components --------------------------------
import Navbar from "./components/Navbar";
// Fonts --------------------------
import { Rubik } from "next/font/google";

// Font --------
const rubik = Rubik({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        
        <Navbar />       
        {children}
      </body>
    </html>
  );
}
